# Generated by Django 5.0.2 on 2024-02-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='symbolmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='NA', max_length=25)),
                ('ltp', models.CharField(default='NA', max_length=25)),
                ('onehr', models.CharField(default='NA', max_length=25)),
                ('onehrprice', models.CharField(default='NA', max_length=25)),
                ('onehrchange', models.CharField(default='NA', max_length=25)),
                ('twohr', models.CharField(default='NA', max_length=25)),
                ('twohrprice', models.CharField(default='NA', max_length=25)),
                ('twohrchange', models.CharField(default='NA', max_length=25)),
                ('totalhr', models.CharField(default='NA', max_length=25)),
                ('totalhrprice', models.CharField(default='NA', max_length=25)),
                ('totalhrchange', models.CharField(default='NA', max_length=25)),
            ],
        ),
    ]
