# Generated by Django 5.0.2 on 2024-02-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolmaster',
            name='type',
            field=models.CharField(default='NA', max_length=25),
        ),
    ]
