# Generated by Django 5.0.2 on 2024-02-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastructure', '0003_alter_symbolmaster_ltp_alter_symbolmaster_onehr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolmaster',
            name='ltp',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='onehr',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='onehrchange',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='onehrprice',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='totalhr',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='totalhrchange',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='totalhrprice',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='twohr',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='twohrchange',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='twohrprice',
            field=models.CharField(default='NA', max_length=25),
        ),
    ]
