# Generated by Django 5.0.2 on 2024-02-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastructure', '0005_alter_symbolmaster_ltp_alter_symbolmaster_onehr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolmaster',
            name='ltp',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='onehr',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='onehrchange',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='onehrprice',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='totalhr',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='totalhrchange',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='totalhrprice',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='twohr',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='twohrchange',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='symbolmaster',
            name='twohrprice',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
    ]
